### ISSUE TITLE
Getting metadata without an obvious key 

### ISSUE THREAD

**Issue by kmbond** [nwilming/pyedfread#12]
Hi again, 

As I'm sure you know, EDF files have a limit of eight characters. To include all the information relating to the experimental session, I embedded information within the EDF file as below: 

[Screen Shot 2019-05-22 at 5.32.24 PM.pdf](https://github.com/nwilming/pyedfread/files/3209402/Screen.Shot.2019-05-22.at.5.32.24.PM.pdf)

Here, the line that reads `786_reward0_[...]` is the relevant piece of information I'd like to extract. Is there a way to get this information with your package? I know that there's a `meta` argument to the `pread` function, but wasn't sure how to specify given there's no obvious key.

Thanks for your patience and your help.

**Comment by nwilming** [comment]
AFAIK this should be saved in the preamble at the top of the EDF. You can read this from the edf using edfread.read_preamble. This should return a string that includes the metadata. Maybe give this a try and let me know if it doesn't work.

**Comment by kmbond** [comment]
That worked perfectly. Thanks again for the great package. I can't imagine how much time this would take otherwise.
