### ISSUE TITLE
No module named 'edf'

### ISSUE THREAD

**Issue by dmardanbeigi** [nwilming/pyedfread#3]
installation seems to be done correctly, but python does not find edf module when trying to import edf! Any hint?!

`running install
running build
running build_py
creating build
creating build/lib.macosx-10.12-x86_64-3.6
creating build/lib.macosx-10.12-x86_64-3.6/pyedfread
copying pyedfread/__init__.py -> build/lib.macosx-10.12-x86_64-3.6/pyedfread
copying pyedfread/edf.py -> build/lib.macosx-10.12-x86_64-3.6/pyedfread
copying pyedfread/test.py -> build/lib.macosx-10.12-x86_64-3.6/pyedfread
running build_ext
cythoning pyedfread/edf_data.pyx to pyedfread/edf_data.c
building 'pyedfread.edf_data' extension
creating build/temp.macosx-10.12-x86_64-3.6
creating build/temp.macosx-10.12-x86_64-3.6/pyedfread
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/lib/python3.6/site-packages/numpy/core/include -I/Library/Frameworks/edfapi.framework/Headers -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c pyedfread/edf_data.c -o build/temp.macosx-10.12-x86_64-3.6/pyedfread/edf_data.o -w
clang -bundle -undefined dynamic_lookup build/temp.macosx-10.12-x86_64-3.6/pyedfread/edf_data.o -L/usr/local/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/sqlite/lib -o build/lib.macosx-10.12-x86_64-3.6/pyedfread/edf_data.cpython-36m-darwin.so -F/Library/Frameworks/ -framework edfapi
cythoning pyedfread/edfread.pyx to pyedfread/edfread.c
building 'pyedfread.edfread' extension
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/lib/python3.6/site-packages/numpy/core/include -I/Library/Frameworks/edfapi.framework/Headers -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c pyedfread/edfread.c -o build/temp.macosx-10.12-x86_64-3.6/pyedfread/edfread.o -w
clang -bundle -undefined dynamic_lookup build/temp.macosx-10.12-x86_64-3.6/pyedfread/edfread.o -L/usr/local/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/sqlite/lib -o build/lib.macosx-10.12-x86_64-3.6/pyedfread/edfread.cpython-36m-darwin.so -F/Library/Frameworks/ -framework edfapi

ld: warning: pointer not aligned at address 0x2ADBB (___pyx_string_tab + 43 from build/temp.macosx-10.12-x86_64-3.6/pyedfread/edfread.o)
ld: warning: pointer not aligned at address 0x2ADB3 (___pyx_string_tab + 35 from build/temp.macosx-10.12-x86_64-3.6/pyedfread/edfread.o)
running build_scripts
creating build/scripts-3.6
copying and adjusting pyedfread/read_edf -> build/scripts-3.6
changing mode of build/scripts-3.6/read_edf from 644 to 755
running install_lib
copying build/lib.macosx-10.12-x86_64-3.6/pyedfread/edf_data.cpython-36m-darwin.so -> /usr/local/lib/python3.6/site-packages/pyedfread
copying build/lib.macosx-10.12-x86_64-3.6/pyedfread/edfread.cpython-36m-darwin.so -> /usr/local/lib/python3.6/site-packages/pyedfread
running install_scripts
copying build/scripts-3.6/read_edf -> /usr/local/bin
changing mode of /usr/local/bin/read_edf to 755
running install_egg_info
Writing /usr/local/lib/python3.6/site-packages/pyedfread-0.1-py3.6.egg-info`

**Comment by dmardanbeigi** [comment]
I tried to reinstall again. Now I can 'import pyedfread' but still 'import edf' does not work!

**Comment by nwilming** [comment]
Sorry for the long delay - I think this is a bug in the doc. Try running 

>>> from pyedfread import edf

and see if this works for you.

**Comment by dmardanbeigi** [comment]
Thanks! Yes 'from pyedfread import edf' works.
