### ISSUE TITLE
support for !CAL msgs

### ISSUE THREAD

**Issue by dmardanbeigi** [nwilming/pyedfread#4]
Hi,
This is not an issue really but could you also add support for `!CAL Calibration points` and `!CAL VALIDATION` massages? (See the example file attached) I'm not sure if the current version supports these two msgs.
Thanks

[sample edf.txt](https://github.com/nwilming/pyedfread/files/1187062/sample.edf.txt)

**Comment by nwilming** [comment]
I've added a function to ('read_calibration') in edfread in branch read_cal. Try this:

`calibration_lines = edfread.read_calibration(b'some_edf.edf')`

If this works for you I can merge into master.

**Comment by dmardanbeigi** [comment]
That works. Thanks again.
