### ISSUE TITLE
filter=['condition']

### ISSUE THREAD

**Issue by selimonat** [nwilming/pyedfread#8]
when not using filter argument, the `messages` DataFrame contains `py_trial_marker` of value -1, which is useful as it contains `DISPLAY_COORDS`. This is necessary to compute define the range of a 2D fixation density map.

However, when `filter=['all']`, this row is missing from the `messages` data frame, which is not clear why.

**Comment by nwilming** [comment]
I think the correct setting to include all fields is `filter='all'` and not `filter=['all']`. In the latter case only the message key 'all' would be included in the message structure (+default trial fields).
