### ISSUE TITLE
stim onsets

### ISSUE THREAD

**Issue by selimonat** [nwilming/pyedfread#9]
Currently fixations are time stamps in system's time during experiment. I wanted to shift time stamps so that they are relative to the stimulus onset. Where do I find stimulus onset?
I have expected SYNCTIME messages to be in the messages dataframe, but no chance. Any idea?

**Comment by nwilming** [comment]
I've just checked the code and SYNCTIME messages get a special treatment and should be included in the output message frame. If not it's a bug. I don't have an EDF file with SYNCTIME, so can't really check this any further at the moment. Can you provide one?
